### PR TITLE
Add PowerToggle and WhiteBalance Modes

### PR DESCRIPTION
**Pull request by yurividal**
This PR adds many missing functionalities for Sony SRG Series.
Power On/Off the Camera, White Balance Control, Brightness, Backlight Compensation, Aperture, Wide Dynamic Range.

### CODE REVIEW

**Comment by McHauge** [comment]
@yurividal just wanna ask, have you tested this implementation?

**Comment by McHauge** [comment]
The first commit looks wrong, in the sense that it changed "everything" but does not look like it broke any thing from what I can see.

**Comment by yurividal** [comment]
@McHauge yes, I tested. I'm actually using it in production with my SRG-300HC camera right now.

And, about the first commit, there are changes, yes. The reason it shows all lines changed is because I replaced the file in the folder with the one I was editing on my work computer. 
But, if you do a diff check with a diff tool, you will se the changes.

**Comment by McHauge** [comment]
Perfect, I'll merge the changes, and then you can make a request in the #module-deveopment chat for it to be included/updated into the companion core, just tag krocheck or JeffreyDavidsz in the message

**Pull request merged**
